spring:
  application:
    name: api-gateway-service
  redis:
    host: localhost
    port: 6379
  jackson:
    default-property-inclusion: non_empty

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            #- StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@userKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
              redis-rate-limiter.requestedTokens: 1
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

server:
  port: 8090

management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"