spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/ums?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ums
  jackson:
    default-property-inclusion: non_empty

server:
  port: 8083
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

springdoc:
  packagesToScan: com.tcs.training

logging:
  level:
    .: INFO

event:
  queue:
    polling-interval: 5000