spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:file:./library-management-system-modularized/book-service/database/bookdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true
      #defer-datasource-initialization: true
      #sql:
    #init:
    #mode: always
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_empty
server:
  port: 8890
  #port: 0
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

springdoc:
  packagesToScan: com.tcs.training.book

logging:
  level:
    .: INFO



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  authorClient:
    name: AuthorAPI
    url: http://localhost:8889/authors
  borrowClient:
    name: BorrowingAPI
    url: http://localhost:8891/borrowings


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false