spring:
  application:
    name: aggregator-service

  jackson:
    default-property-inclusion: non_empty
server:
  #port: 8890
  port: 0
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

springdoc:
  packagesToScan: com.tcs.training

logging:
  level:
    .: INFO



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  customerClient:
    name: customer-service
  productClient:
    name: product-service
  orderClient:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false