spring:
  application:
    name: api-gateway-service
  redis:
    host: localhost
    port: 6379
  jackson:
    default-property-inclusion: non_empty

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: author-service
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/authors/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            #- StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@userKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
              redis-rate-limiter.requestedTokens: 1
        - id: borrowing-service
          uri: lb://BORROWING-SERVICE
          predicates:
            - Path=/borrowings/**

server:
  port: 8090

management:
  health:
    redis:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true