spring:
  application:
    name: author-service
  datasource:
    url: jdbc:h2:file:./library-management-system-modularized/author-service/database/authordb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true
      #defer-datasource-initialization: true
      #sql:
    #init:
    #mode: always
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_empty
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    openfeign:
      lazy-attributes-resolution: true

server:
  #port: 8889
  port: 0
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

springdoc:
  packagesToScan: com.tcs.training.author

logging:
  level:
    .: INFO



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  bookClient:
    name: book-service
    url: http://localhost:8890/books


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false