spring:
  application:
    name: observability-service
  jackson:
    default-property-inclusion: non_empty

server:
  port: 9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    preferIpAddress: true